export const SELECT_USERNAME = "SELECT_USERNAME";
export const SUBMIT_USERNAME = "SUBMIT_USERNAME";
export const AUTH_ERROR_SOCKET = "AUTH_ERROR_SOCKET";

export const CONNECTED_USERS = "CONNECTED_USERS";
export const SELECT_USER = "SELECT_USER";
export const LOGOUT_USER = "LOGOUT_USER";



